#application.yml
server:
  port: 12000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.136.129
    port: 6379
  application:
    name: gulimall-search

