#application.yml
server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route1
          uri: http://localhost:7000/
          predicates:
            # 当访问http://localhost:88/coupon/coupon/list路由到localhost:7000/coupon/coupon/list
            - Path=/coupon/coupon/list

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            # 当访问http://localhost:88/api/product/**路由到http://localhost:对应端口/**
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            # 当访问http://localhost:88/api/**路由到http://localhost:对应端口/**
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
  application:
    name: gulimall-gateway