#application.yml
server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: test_route1
          uri: http://localhost:7000/
          predicates:
            # 当访问http://localhost:88/coupon/coupon/list路由到localhost:7000/coupon/coupon/list
            - Path=/coupon/coupon/list

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            # 当访问http://localhost:88/api/product/**路由到http://localhost:对应端口/product/**
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

          #http://localhost:88/api/thirdparty/oss/policy转发到http://localhost:30000/oss/policy
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
          # 当访问http://localhost:88/api/thirdparty/**路由到http://localhost:对应端口/thirdparty/**
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            # 当访问http://localhost:88/api/**路由到http://localhost:对应端口/**
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: mall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=mall.com,item.mall.com

        - id: mall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.mall.com

        - id: mall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.mall.com

        - id: mall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.mall.com
  application:
    name: gulimall-gateway